"""Añade la tabla RecurringTransaction

Revision ID: 7dfb037d3067
Revises: ff149808c583
Create Date: 2025-09-17 13:48:48.345954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfb037d3067'
down_revision = 'ff149808c583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('next_date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_transaction_next_date'), ['next_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_transaction_next_date'))

    op.drop_table('recurring_transaction')
    # ### end Alembic commands ###
